import type { Amount, Psbt, ScriptBuf, Transaction } from '@metamask/bitcoindevkit';
import { TransactionType } from '@metamask/keyring-api';

import type { BitcoinAccount } from './account';

/**
 * Resolves the transaction classification for a Bitcoin transaction.
 *
 * Bitcoin has no contract calls, so a transaction is either outgoing (`send`,
 * including self-sends and consolidations) or incoming (`receive`). Used both
 * for the keyring transaction payload and for the `transaction_type` analytics
 * dimension, so the two can never disagree.
 *
 * @param account - The account the transaction belongs to.
 * @param tx - The raw Bitcoin transaction.
 * @returns The transaction type.
 */
export function mapToTransactionType(
  account: BitcoinAccount,
  tx: Transaction,
): TransactionType {
  const [sent] = account.sentAndReceived(tx);
  return sent.to_btc() > 0 ? TransactionType.Send : TransactionType.Receive;
}

/**
 * A Bitcoin transaction builder.
 */
export type TransactionBuilder = {
  /**
   * Add a new recipient the PSBT.
   *
   * @param amount - The amount in satoshis
   * @param recipientAddress - The recipient address
   */
  addRecipient(amount: string, recipientAddress: string): TransactionBuilder;

  /**
   * Add a new recipient the PSBT by script pubkey.
   *
   * @param amount - The amount in satoshis
   * @param recipientScriptPubkey - The recipient script public key
   */
  addRecipientByScript(
    amount: Amount,
    recipientScriptPubkey: ScriptBuf,
  ): TransactionBuilder;

  /**
   * Set the PSBT fee rate.
   *
   * @param feeRate - The fee rate in sat/vB
   */
  feeRate(feeRate: number): TransactionBuilder;

  /**
   * Spend all the available inputs. This respects filters like `unspendable` and the change policy.
   */
  drainWallet(): TransactionBuilder;

  /**
   * Sets the address to *drain* excess coins to.
   *
   * Usually, when there are excess coins they are sent to a change address generated by the
   * wallet. This option replaces the usual change address with an arbitrary `script_pubkey` of
   * your choosing.
   *
   * @param address - The recipient address
   */
  drainTo(address: string): TransactionBuilder;

  /**
   * Sets the script to *drain* excess coins to.
   *
   * Usually, when there are excess coins they are sent to a change address generated by the
   * wallet. This option replaces the usual change address with an arbitrary `script_pubkey` of
   * your choosing.
   *
   * @param scriptPubKey - The recipient script
   */
  drainToByScript(scriptPubKey: ScriptBuf): TransactionBuilder;

  /**
   * Set the list of unspendable UTXOs. These outpoints won't be selected by the coin selection algorithm.
   *
   * @param unspendable - The list of unspendable UTXO outpoints.
   */
  unspendable(unspendable: string[]): TransactionBuilder;

  /**
   * Set the ordering for inputs and outputs of the transaction to untouched.
   */
  untouchedOrdering(): TransactionBuilder;

  /**
   * Creates the PSBT.
   *
   * @returns the PSBT
   */
  finish(): Psbt;
};
