name: Publish a preview build

on:
  issue_comment:
    types: created

permissions:
  contents: read
  pull-requests: write

jobs:
  publish-preview:
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '@metamaskbot publish-preview') }}
    uses: MetaMask/github-tools/.github/workflows/publish-preview.yml@v1
    with:
      rename-after-install-and-build: true
      environment: default-branch
      docs-url: 'https://github.com/MetaMask/core/blob/main/docs/processes/preview-builds.md'
    secrets:
      PUBLISH_PREVIEW_NPM_TOKEN: ${{ secrets.PUBLISH_PREVIEW_NPM_TOKEN }}
      BUILD_ENV: |
        {
          "LOG_LEVEL": "${{ secrets.LOG_LEVEL }}",
          "DEFAULT_ADDRESS_TYPE": "${{ secrets.DEFAULT_ADDRESS_TYPE }}",
          "ESPLORA_BITCOIN": "${{ secrets.ESPLORA_BITCOIN }}",
          "ESPLORA_TESTNET": "${{ secrets.ESPLORA_TESTNET }}",
          "ESPLORA_TESTNET4": "${{ secrets.ESPLORA_TESTNET4 }}",
          "ESPLORA_SIGNET": "${{ secrets.ESPLORA_SIGNET }}",
          "ESPLORA_REGTEST": "${{ secrets.ESPLORA_REGTEST }}",
          "PRICE_API_URL": "${{ secrets.PRICE_API_URL }}",
          "PRICE_API_BASE_URL": "${{ vars.PRICE_API_BASE_URL }}",
          "ENVIRONMENT": "production",
          "RPC_URL_LIST_MAINNET": "${{ secrets.RPC_URL_LIST_MAINNET }}",
          "RPC_URL_LIST_NILE_TESTNET": "${{ vars.RPC_URL_LIST_NILE_TESTNET }}",
          "RPC_URL_LIST_SHASTA_TESTNET": "${{ vars.RPC_URL_LIST_SHASTA_TESTNET }}",
          "LOCAL_API_BASE_URL": "${{ vars.LOCAL_API_BASE_URL }}",
          "TOKEN_API_BASE_URL": "${{ vars.TOKEN_API_BASE_URL }}",
          "STATIC_API_BASE_URL": "${{ vars.STATIC_API_BASE_URL }}",
          "SECURITY_ALERTS_API_BASE_URL": "${{ vars.SECURITY_ALERTS_API_BASE_URL }}",
          "NFT_API_BASE_URL": "${{ vars.NFT_API_BASE_URL }}",
          "EXPLORER_MAINNET_BASE_URL": "${{ vars.EXPLORER_MAINNET_BASE_URL }}",
          "EXPLORER_NILE_BASE_URL": "${{ vars.EXPLORER_NILE_BASE_URL }}",
          "EXPLORER_SHASTA_BASE_URL": "${{ vars.EXPLORER_SHASTA_BASE_URL }}",
          "TRONGRID_BASE_URL_MAINNET": "${{ secrets.TRONGRID_BASE_URL_MAINNET }}",
          "TRONGRID_BASE_URL_NILE": "${{ vars.TRONGRID_BASE_URL_NILE }}",
          "TRONGRID_BASE_URL_SHASTA": "${{ vars.TRONGRID_BASE_URL_SHASTA }}",
          "TRON_HTTP_BASE_URL_MAINNET": "${{ secrets.TRON_HTTP_BASE_URL_MAINNET }}",
          "TRON_HTTP_BASE_URL_NILE": "${{ vars.TRON_HTTP_BASE_URL_NILE }}",
          "TRON_HTTP_BASE_URL_SHASTA": "${{ vars.TRON_HTTP_BASE_URL_SHASTA }}",
          "RPC_URL_MAINNET_LIST": "${{ secrets.RPC_URL_MAINNET_LIST }}",
          "RPC_URL_DEVNET_LIST": "${{ secrets.RPC_URL_DEVNET_LIST }}",
          "RPC_URL_TESTNET_LIST": "${{ vars.RPC_URL_TESTNET_LIST }}",
          "RPC_URL_LOCALNET_LIST": "${{ vars.RPC_URL_LOCALNET_LIST }}",
          "RPC_WEB_SOCKET_URL_MAINNET": "${{ secrets.RPC_WEB_SOCKET_URL_MAINNET }}",
          "RPC_WEB_SOCKET_URL_DEVNET": "${{ secrets.RPC_WEB_SOCKET_URL_DEVNET }}",
          "RPC_WEB_SOCKET_URL_TESTNET": "${{ vars.RPC_WEB_SOCKET_URL_TESTNET }}",
          "RPC_WEB_SOCKET_URL_LOCALNET": "${{ vars.RPC_WEB_SOCKET_URL_LOCALNET }}",
          "EXPLORER_BASE_URL": "${{ vars.EXPLORER_BASE_URL }}"
        }
