name: Publish a preview build

on:
  issue_comment:
    types: created

permissions:
  contents: read
  pull-requests: write

jobs:
  publish-preview:
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '@metamaskbot publish-preview') }}
    uses: MetaMask/github-tools/.github/workflows/publish-preview.yml@v1
    with:
      rename-after-install-and-build: true
      environment: default-branch
      docs-url: 'https://github.com/MetaMask/core/blob/main/docs/processes/preview-builds.md'
    secrets:
      PUBLISH_PREVIEW_NPM_TOKEN: ${{ secrets.PUBLISH_PREVIEW_NPM_TOKEN }}
      BUILD_ENV: |
        {
          "LOG_LEVEL": "all",
          "DEFAULT_ADDRESS_TYPE": "${{ secrets.DEFAULT_ADDRESS_TYPE }}",
          "ESPLORA_BITCOIN": "${{ secrets.ESPLORA_BITCOIN }}",
          "ESPLORA_TESTNET": "${{ secrets.ESPLORA_TESTNET }}",
          "ESPLORA_TESTNET4": "${{ secrets.ESPLORA_TESTNET4 }}",
          "ESPLORA_SIGNET": "${{ secrets.ESPLORA_SIGNET }}",
          "ESPLORA_REGTEST": "${{ secrets.ESPLORA_REGTEST }}",
          "PRICE_API_URL": "${{ secrets.PRICE_API_URL }}"
        }
