name: SonarCloud

permissions:
  contents: read
  pull-requests: write
  checks: write

on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        description: SonarCloud token
        required: true

jobs:
  sonarcloud-scan:
    name: SonarCloud scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and setup environment
        uses: MetaMask/action-checkout-and-setup@v3
        with:
          is-high-risk-environment: false
          # SonarCloud needs the full history for new-code and blame data
          fetch-depth: 0

      - name: Download coverage artifacts
        uses: actions/download-artifact@v7
        with:
          pattern: coverage-*
          path: packages
          merge-multiple: true

      - name: Display coverage artifacts
        run: ls packages/*/coverage/lcov.info
        shell: bash

      - name: SonarCloud scan
        # This is SonarSource/sonarqube-scan-action@v7.1.0
        uses: SonarSource/sonarqube-scan-action@299e4b793aaa83bf2aba7c9c14bedbb485688ec4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
